swagger: '2.0'
info:
  title: ScaleManager Collector API
  description: ScaleManager Collector API for collecting data from the instances
  version: "1.0.0"
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /state:
    post:
      summary: Collects data for the ScaleManager for further usage
      description: Collects data from various instances to further use it in the ScaleManager.
      parameters:
        - name: type
          in: body
          schema:
            $ref: '#/definitions/State'
          description: Current state
          required: true
      responses:
        202:
          description: State was accepted
definitions:
  State:
    type: object
    properties:
      type:
        type: string
        description: Type of the state, e.g. memory or cpu-load.
      value:
        type: string
        description: The value the state has. In case of memory its the actual size in KB.
      instance:
        type: string
        description: The ID of the instance.
      timestamp:
        type: integer
        format: int32
        description: The timestamp the state was recorded at.